image: docker:latest

services:
  - docker:dind

stages:
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2

build_image:
  stage: build
  script:
    - docker build -t zako2294/webapp:latest .

push_image:
  stage: push
  script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
    - docker push zako2294/webapp:latest
